package com.enums;

public enum Color {
    RED, GREEN, BLUE, BLACK, GRAY, SILVER, WHITE, PINK, PURPLE, VIOLET, ORANGE, GOLD, DARK_GRAY, LIGHT_GRAY,
    TAN, FOREST, OCHRE, TANGERINE, PEACH, PLUM, BROWN, CREAM, INDIGO, MARINE, MOSS, KELLY, SAGE;
}
